name: Learn Github Actions
on: [push]
jobs:
    checks-bats-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkouts@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '14'
        - run: npm install -g bats
        - run: bats -v
