name: Run Shell Scripts


on: [push]
jobs:
    run-first-script:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Give Permission to the shell script
          run: chmod +x .github/common/env.sh

        - name: Execute script 1
          run: .github/common/env.sh
          shell: bash


    run-second-script:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Give Permission to the shell script
          run: chmod +x .github/common/env_1.sh

        - name: Execute script 2
          run: .github/common/env_1.sh
          shell: bash
